@SchoolSystem.Api_HostAddress = http://localhost:5282

GET {{SchoolSystem.Api_HostAddress}}/api/rooms
Accept: application/json

###


GET {{SchoolSystem.Api_HostAddress}}/api/rooms/2
Accept: application/json

###

GET {{SchoolSystem.Api_HostAddress}}/api/rooms/xyz-3
Accept: application/json

###

POST {{SchoolSystem.Api_HostAddress}}/api/rooms
Accept: application/json
Content-Type: application/json

{
    "Capacity": -4
    ,
    "Location": "FR01"
}

###
PUT {{SchoolSystem.Api_HostAddress}}/api/rooms/2
Accept: application/json
Content-Type: application/json

{
    "Capacity": 26,
    "Location": "FR01"
}

###

DELETE {{SchoolSystem.Api_HostAddress}}/api/rooms/1
Accept: application/json

##############


GET {{SchoolSystem.Api_HostAddress}}/api/users/students
Accept: application/json

###


GET {{SchoolSystem.Api_HostAddress}}/api/users/students/2
Accept: application/json

###

GET {{SchoolSystem.Api_HostAddress}}/api/users/students/MAT-2024-2
Accept: application/json

###

POST {{SchoolSystem.Api_HostAddress}}/api/users/students
Accept: application/json
Content-Type: application/json

{
    "firstName": "Mary",
    "lastName": "Smither",
    "email": ",ary@email.com",
    "address": "calle B",
    "birthday": "2001-03-25"
}

###
PUT {{SchoolSystem.Api_HostAddress}}/api/users/students/4
Accept: application/json
Content-Type: application/json

{
    "firstName": "Mary",
    "lastName": "Smither",
    "email": "mary@email.com",
    "address": "calle B",
    "birthday": "2001-03-25",
    "fatherName": "Bob Smither",
    "motherName": "Martha Clint"
}

###

DELETE {{SchoolSystem.Api_HostAddress}}/api/users/students/3
Accept: application/json

    
##############


GET {{SchoolSystem.Api_HostAddress}}/api/users/teachers
Accept: application/json

###


GET {{SchoolSystem.Api_HostAddress}}/api/users/teachers/2
Accept: application/json

###

GET {{SchoolSystem.Api_HostAddress}}/api/users/teachers/MAT-2024-2
Accept: application/json

###

POST {{SchoolSystem.Api_HostAddress}}/api/users/teachers
Accept: application/json
Content-Type: application/json

{
    "firstName": "Mary",
    "lastName": "Smither",
    "email": ",ary@email.com",
    "address": "calle B",
    "subject": "Maths"
}

###
PUT {{SchoolSystem.Api_HostAddress}}/api/users/teachers/1
Accept: application/json
Content-Type: application/json

{
    "firstName": "Richard",
    "lastName": "Kidder",
    "email": "rich@email.com",
    "address": "calle B2",
    "subject": "Maths"
}

###

DELETE {{SchoolSystem.Api_HostAddress}}/api/users/teachers/3
Accept: application/json
    
##############


GET {{SchoolSystem.Api_HostAddress}}/api/schedules
Accept: application/json

###


GET {{SchoolSystem.Api_HostAddress}}/api/schedules/2
Accept: application/json

###

GET {{SchoolSystem.Api_HostAddress}}/api/schedules/MAT-2024-2
Accept: application/json

###

POST {{SchoolSystem.Api_HostAddress}}/api/schedules
Accept: application/json
Content-Type: application/json

{
    "startTime": "10:00:00",
    "finishTime": "11:00:00",
    "day": 1,
    "roomId": 1,
    "teacherId": 33
}

###
PUT {{SchoolSystem.Api_HostAddress}}/api/schedules/1
Accept: application/json
Content-Type: application/json

{
    "firstName": "Richard",
    "lastName": "Kidder",
    "email": "rich@email.com",
    "address": "calle B2",
    "subject": "Maths"
}

###

DELETE {{SchoolSystem.Api_HostAddress}}/api/schedules/4
Accept: application/json